### ISSUE TITLE
Verify that major version updates to peer dependencies are working

### ISSUE THREAD

**Issue by kristerkari** [kristerkari/observable-redux-json-api#48]
After releasing version 1.0.0 of `observable-redux-json-api` all the peer dependencies have had a major version release. One of the issues that I have already identified is with the breaking changes between Typescript types of redux 4.0.0/redux-thunk 2.3.0.

**Check compatiblity with these library versions:**
* redux-observable 1.x
* redux 4.x / redux-thunk 2.3.0
* RxJS 6.x

**TODO:**

- [ ] Update both JS example app and TS example app to not use `store.dispatch` (removed in redux-observable v1).
- [ ] Update JS example app to use RxJS v6.
- [ ] Update TS example app to use RxJS v6.
- [ ] Update `observable-redux-json-api` types to support Redux v4
- [ ] Update JS example app to redux 4.x / redux-thunk 2.3.0
- [ ] Update TS example app to redux 4.x / redux-thunk 2.3.0
